from sasram.mcp import tool
import requests
import duckdb as dd
import pandas as pd
import matplotlib.pyplot as plt
import io
import base64
from typing import Tuple
import json
from io import BytesIO
from langchain_core.messages import HumanMessage
import os

categ_file = os.getenv("categ_file")
inventory_file = os.getenv("inventory_file")
print(f"CATEGORIZATION file is {categ_file} and INVENTORY file is {inventory_file}")

con = dd.connect()
con.execute("INSTALL httpfs;")
con.execute("LOAD httpfs;")

print(f"Duck DB connected")

con.execute(f"CREATE OR REPLACE TABLE CC AS SELECT * FROM read_parquet('{categ_file}') ;")
con.execute(f"CREATE OR REPLACE TABLE INV AS SELECT * FROM read_parquet('{inventory_file}') ;")

print("Tables created")

@tool
def lookup_data_references() -> dict:
    """Informs calling agent about the path to data files"""
    return {"CATEGORIZATION File":categ_file, "STOCK File": inventory_file}

@tool
def run_generated_duckdb_sql(gen_sql: str) -> dict:
    """Given a SQL in Duck DB dialect generated by LLM, executes the same and returns the result"""
    res = con.execute(gen_sql)
    arrs = res.fetchnumpy()   # returns dict: {column_name: numpy_array}
    result_dict = {k: v.tolist() for k, v in arrs.items()}
    return result_dict


@tool
def get_nbr_categorized_items() -> int:
    """Retrieves the total number of items categorized from the scoring domain."""
    nbr_items = con.execute("SELECT COUNT(*) as nbr_items FROM CC;").fetchone()[0]
    return nbr_items


@tool
def get_nbr_inventory_items() -> int:
    """Retrieves the total number of items in the inventory."""
    nbr_items = con.execute("SELECT COUNT(*) as nbr_items FROM INV;").fetchone()[0]
    return nbr_items


@tool
def get_inventory_from_sku(sku: str) -> int:
    """Retrieves the inventory of an item specified with its sku iitem value."""
    inventory_for_item = con.execute(
        "SELECT inventory FROM INV WHERE item_sku = ?", [str(sku)]
    ).fetchone()[0]
    return inventory_for_item


@tool
def get_purchased_quantity_from_sku(sku: str) -> int:
    """Retrieves the purchased quantity for an item specified with its sku id value."""
    purchased_for_item = con.execute(f"SELECT item_sku, item_designation, purchased_quantity FROM INV WHERE item_sku= = ?", [str(sku)]
    ).fetchone()[0]
    return purchased_for_item


